---
# Mail server sonfiguration script
- ansible.builtin.include_tasks: sendmail.yml
  when: mail_sender == "sendmail"
- ansible.builtin.include_tasks: postfix.yml
  when: mail_sender == "postfix"
- ansible.builtin.include_tasks: opendkim.yml
  when: postfix_opendkim == True
